### PR TITLE
SSO-401 fixing issue with user extension

### PR DESCRIPTION
**Pull request by DataScan-Development**
This fix is related to the following reported Bettercloud/scim2 GitHub:

[Schema endpoint to include extensions · Issue #1 · BetterCloud/scim2](https://github.com/BetterCloud/scim2/issues/1)

### CODE REVIEW

**Review by DataScan-Development — COMMENTED** [review]
jjprokash:
List<SchemaResource> resourceList = new ArrayList<>(resourceTypeDefinition.getSchemaExtensions().keySet());
resourceList.add(resourceTypeDefinition.getCoreSchema());

**Comment by alexmaldonado22** [comment]
@jjprokash: I don't think we can use resourceList.add(resourceTypeDefinition.getCoreSchema());

We need to add collection to list.
resourceList.addAll(Collections.singletonList(resourceTypeDefinition.getCoreSchema()));

**Comment by alexmaldonado22** [comment]
@jjprokash I pushed changes.

**Review by rsadekar — APPROVED** [review]
Changes look good.

**Comment by DataScan-Development** [comment]
jjprokash: looks good

**Pull request merged**
